[toolchain]
channel = "stable"
components = ["rustfmt", "clippy"]
targets = [
    # "x86_64-unknown-linux-gnu",    # Linux (x86_64)
    # "x86_64-apple-darwin",         # macOS (x86_64)
    "x86_64-pc-windows-msvc",      # Windows (x86_64)
    # "aarch64-apple-darwin"         # macOS (ARM64)
]